dist: focal
language: csharp
mono: none
dotnet: 8.0
solution: MyWebApp.sln

services:
  - docker

before_install:
  - sudo apt-get update
  - sudo apt-get install -y awscli

install:
  - dotnet restore

script:
  - dotnet build
  - dotnet test MyWebApp.Tests/MyWebApp.Tests.csproj

before_deploy:
  - chmod +x deploy.sh
  - docker images
  - docker build -t vladprytamannyi/mywebapp:latest .
  - docker images

deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: main