dist: focal
language: csharp
mono: none
dotnet: 8.0
solution: MyWebApp.sln

install:
  - dotnet restore

script:
  - dotnet build
  - dotnet test MyWebApp.Tests/MyWebApp.Tests.csproj

before_deploy:
  - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
  - unzip awscliv2.zip
  - sudo ./aws/install
  - docker build -t mywebapp .

deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: main