dist: focal
language: csharp
mono: none
dotnet: 8.0
solution: MyWebApp.sln

services:
  - docker

before_install:
  - sudo apt-getinstall -y awscli

install:
  - dotnet restore

script:
  - dotnet build
  - dotnet test MyWebApp.Tests/MyWebApp.Tests.csproj

before_deploy:
  - docker build -t mywebapp .
  - chmod +x deploy.sh

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: main