dist: focal
language: csharp
mono: none
dotnet: 8.0
solution: MyWebApp.sln

services:
  - docker


install:
  - dotnet restore

script:
  - dotnet build
  - dotnet test MyWebApp.Tests/MyWebApp.Tests.csproj

before_deploy:
  - chmod +x deploy.sh

deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: main